name: funny_bot
description: A funny chatbot using Flutter and OpenAI
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  logging: ^1.3.0
  google_generative_ai: ^0.0.1-dev
  flutter_gemini: ^2.0.3
  shared_preferences: ^2.2.2
  flutter_tts: ^3.8.4  # Keep only one version of flutter_tts
  logger: ^1.0.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  assets:
    - .env
  uses-material-design: true
